---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nginx-charts
  namespace: flux-system
spec:
  interval: 15m
  url: https://helm.traefik.io/traefi://helm.nginx.com/stable 
  timeout: 3m
