---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-external
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.traefik.io/traefik
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: nginx-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  values:
    controller:
      ingressClass: external
      kind: Deployment
      config:
        use-forwarded-headers: "true"
      extraArgs:
        default-ssl-certificate: 'nginx/x-ctr-farm-cert'
      extraEnvs:
        - name: TZ
          value: America/Chicago
      metrics:
        enabled: true
        #serviceMonitor:
          #enabled: true
          #namespace: kube-system
      service:
        annotations:
          prometheus.io/port: "18080"
          prometheus.io/scrape: "true"
        externalTrafficPolicy: Local
        type: LoadBalancer
    defaultBackend:
      enabled: false
